# permissions for end users to edit dbaasredisadapters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dbaasredisadapter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-oper
    app.kubernetes.io/part-of: redis-oper
    app.kubernetes.io/managed-by: kustomize
  name: dbaasredisadapter-editor-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - dbaasredisadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - dbaasredisadapters/status
  verbs:
  - get
