# permissions for end users to view dbaasredisadapters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dbaasredisadapter-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-oper
    app.kubernetes.io/part-of: redis-oper
    app.kubernetes.io/managed-by: kustomize
  name: dbaasredisadapter-viewer-role
rules:
- apiGroups:
  - qubership.org
  resources:
  - dbaasredisadapters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qubership.org
  resources:
  - dbaasredisadapters/status
  verbs:
  - get
