kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-default-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.defaultLabels" . | nindent 4 }}
data:
  config: |-
{{ .Values.redis.conf | toYaml  | indent 4}} 