{{ if .Values.roleBinding.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dbaas-redis-operator
  labels:
    {{- include "redis.defaultLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: dbaas-redis-operator
roleRef:
  kind: Role
  name: dbaas-redis-operator
  apiGroup: rbac.authorization.k8s.io
{{ end }}