{{- if and .Values.redis.tls.enabled .Values.redis.tls.generateCerts.enabled (not (.Values.redis.tls.generateCerts.clusterIssuerName)) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-tls-issuer
spec:
  selfSigned: {}
{{- end }}