{{- if eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) "true" }}
 {{- if .Values.CLOUD_PUBLIC_HOST }}
 {{template "nosql.core.secret.internal" (dict "values" . "vltEnabled" .Values.vaultRegistration.enabled "vltPath" (printf "secret/nc-%s/%s/%s/%s#password" .Values.CLOUD_PUBLIC_HOST .Release.Namespace .Values.serviceAccountName .Values.dbaas.aggregator.secretName) "secret" .Values.dbaas.aggregator)}}
 {{ else }}
 {{template "nosql.core.secret.internal" (dict "values" . "vltEnabled" .Values.vaultRegistration.enabled "vltPath" .Values.vaultRegistration.path "secret" .Values.dbaas.aggregator)}}
 {{ end }}
---
{{template "nosql.core.secret.vault.fromEnv" (dict "values" . "isInternal" false "vlt" .Values.vaultRegistration "secret" .Values.dbaas.aggregator "userEnv" .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME "passEnv" .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD)}}
{{end}}
