{{- if eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) "true" }}
 {{- if .Values.CLOUD_PUBLIC_HOST }}
 {{template "nosql.core.secret.internal" (dict "values" . "vltEnabled" false "vltPath" "" "secret" .Values.dbaas.aggregator)}}
 {{ else }}
 {{template "nosql.core.secret.internal" (dict "values" . "vltEnabled" false "vltPath" "" "secret" .Values.dbaas.aggregator)}}
 {{ end }}
---
{{end}}
