{{- if .Values.vaultRegistration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret-services
  labels:
    {{- include "redis.defaultLabels" . | nindent 4 }}
data:
  {{- if .Values.VAULT_TOKEN }}
  token: {{ .Values.VAULT_TOKEN | b64enc }}
  {{- else }}
  token: {{ default "#" .Values.vaultRegistration.token | b64enc }}
  {{- end }}
type: Opaque
{{- end }}
